// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCorporationEmployeeDepartment = "corporation_employee_department"

// CorporationEmployeeDepartment Employee Department Relationship Table
type CorporationEmployeeDepartment struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:Relationship ID" json:"id"`              // Relationship ID
	EmployeeID   int64  `gorm:"column:employee_id;not null;comment:Employee ID" json:"employee_id"`                     // Employee ID
	DepartmentID int64  `gorm:"column:department_id;not null;comment:Department ID" json:"department_id"`               // Department ID
	JobTitle     string `gorm:"column:job_title;comment:Job Title" json:"job_title"`                                    // Job Title
	Status       int32  `gorm:"column:status;not null;default:1;comment:Status: 1-Active, 2-Transferred" json:"status"` // Status: 1-Active, 2-Transferred
	CreatorID    int64  `gorm:"column:creator_id;not null;comment:Creator ID" json:"creator_id"`                        // Creator ID
	CreatedAt    int64  `gorm:"column:created_at;not null;comment:Create Time in Milliseconds" json:"created_at"`       // Create Time in Milliseconds
	UpdatedAt    int64  `gorm:"column:updated_at;not null;comment:Update Time in Milliseconds" json:"updated_at"`       // Update Time in Milliseconds
	DeletedAt    int64  `gorm:"column:deleted_at;comment:Delete Time in Milliseconds" json:"deleted_at"`                // Delete Time in Milliseconds
}

// TableName CorporationEmployeeDepartment's table name
func (*CorporationEmployeeDepartment) TableName() string {
	return TableNameCorporationEmployeeDepartment
}
