// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCorporationDepartment = "corporation_department"

// CorporationDepartment Department Info Table
type CorporationDepartment struct {
	ID               int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:Department ID" json:"id"`                                                 // Department ID
	CorpID           int64  `gorm:"column:corp_id;not null;comment:Corporation ID" json:"corp_id"`                                                           // Corporation ID
	ParentID         int64  `gorm:"column:parent_id;comment:Parent Department ID (NULL for root department)" json:"parent_id"`                               // Parent Department ID (NULL for root department)
	Name             string `gorm:"column:name;not null;comment:Department Name" json:"name"`                                                                // Department Name
	Code             string `gorm:"column:code;comment:Department Code" json:"code"`                                                                         // Department Code
	Level            int32  `gorm:"column:level;not null;default:1;comment:Department Level" json:"level"`                                                   // Department Level
	FullPath         string `gorm:"column:full_path;comment:Department Full Path" json:"full_path"`                                                          // Department Full Path
	LeaderID         int64  `gorm:"column:leader_id;comment:Department Leader ID" json:"leader_id"`                                                          // Department Leader ID
	Sort             int32  `gorm:"column:sort;not null;comment:Sort Order" json:"sort"`                                                                     // Sort Order
	Status           int32  `gorm:"column:status;not null;default:1;comment:Status: 1-Active, 2-Inactive" json:"status"`                                     // Status: 1-Active, 2-Inactive
	OutDepartmentID  string `gorm:"column:out_department_id;comment:External Department ID" json:"out_department_id"`                                        // External Department ID
	DepartmentSource int32  `gorm:"column:department_source;comment:Data Source: 1-Enterprise WeChat,2-DingTalk,3-Feishu,4-Manual" json:"department_source"` // Data Source: 1-Enterprise WeChat,2-DingTalk,3-Feishu,4-Manual
	CreatorID        int64  `gorm:"column:creator_id;not null;comment:Creator ID" json:"creator_id"`                                                         // Creator ID
	CreatedAt        int64  `gorm:"column:created_at;not null;comment:Create Time in Milliseconds" json:"created_at"`                                        // Create Time in Milliseconds
	UpdatedAt        int64  `gorm:"column:updated_at;not null;comment:Update Time in Milliseconds" json:"updated_at"`                                        // Update Time in Milliseconds
	DeletedAt        int64  `gorm:"column:deleted_at;comment:Delete Time in Milliseconds" json:"deleted_at"`                                                 // Delete Time in Milliseconds
}

// TableName CorporationDepartment's table name
func (*CorporationDepartment) TableName() string {
	return TableNameCorporationDepartment
}
