// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCorporation = "corporation"

// Corporation Corporation Info Table
type Corporation struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:Corporation ID" json:"id"`                                    // Corporation ID
	ParentID   int64  `gorm:"column:parent_id;comment:Parent Corporation ID (NULL for root corporation)" json:"parent_id"`                 // Parent Corporation ID (NULL for root corporation)
	Name       string `gorm:"column:name;not null;comment:Corporation Name" json:"name"`                                                   // Corporation Name
	CorpType   string `gorm:"column:corp_type;not null;default:company;comment:Corporation Type: group,company,branch" json:"corp_type"`   // Corporation Type: group,company,branch
	Sort       int32  `gorm:"column:sort;not null;comment:Sort Order" json:"sort"`                                                         // Sort Order
	OutCorpID  string `gorm:"column:out_corp_id;comment:External Corporation ID" json:"out_corp_id"`                                       // External Corporation ID
	CorpSource int32  `gorm:"column:corp_source;comment:Data Source: 1-Enterprise WeChat,2-DingTalk,3-Feishu,4-Manual" json:"corp_source"` // Data Source: 1-Enterprise WeChat,2-DingTalk,3-Feishu,4-Manual
	CreatorID  int64  `gorm:"column:creator_id;not null;comment:Creator ID" json:"creator_id"`                                             // Creator ID
	CreatedAt  int64  `gorm:"column:created_at;not null;comment:Create Time in Milliseconds" json:"created_at"`                            // Create Time in Milliseconds
	UpdatedAt  int64  `gorm:"column:updated_at;not null;comment:Update Time in Milliseconds" json:"updated_at"`                            // Update Time in Milliseconds
	DeletedAt  int64  `gorm:"column:deleted_at;comment:Delete Time in Milliseconds" json:"deleted_at"`                                     // Delete Time in Milliseconds
}

// TableName Corporation's table name
func (*Corporation) TableName() string {
	return TableNameCorporation
}
