/*
 * Copyright 2025 coze-plus Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameCorporationEmployeeDepartment = "corporation_employee_department"

// CorporationEmployeeDepartment Employee Department Relationship Table
type CorporationEmployeeDepartment struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:Relationship ID" json:"id"`                             // Relationship ID
	EmployeeID   int64          `gorm:"column:employee_id;not null;comment:Employee ID" json:"employee_id"`                                    // Employee ID
	DepartmentID int64          `gorm:"column:department_id;not null;comment:Department ID" json:"department_id"`                              // Department ID
	CorpID       int64          `gorm:"column:corp_id;not null;comment:Corporation ID (department's corporation)" json:"corp_id"`              // Corporation ID (department's corporation)
	JobTitle     *string        `gorm:"column:job_title;comment:Job Title" json:"job_title"`                                                   // Job Title
	IsPrimary    int32          `gorm:"column:is_primary;not null;comment:Is Primary Department: 0-No, 1-Yes" json:"is_primary"`               // Is Primary Department: 0-No, 1-Yes
	Status       int32          `gorm:"column:status;not null;default:1;comment:Status: 1-Active, 2-Transferred" json:"status"`                // Status: 1-Active, 2-Transferred
	CreatorID    int64          `gorm:"column:creator_id;not null;comment:Creator ID" json:"creator_id"`                                       // Creator ID
	CreatedAt    int64          `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
	UpdatedAt    int64          `gorm:"column:updated_at;not null;autoUpdateTime:milli;comment:Update Time in Milliseconds" json:"updated_at"` // Update Time in Milliseconds
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;comment:Deletion timestamp" json:"deleted_at"`                                        // Deletion timestamp
}

// TableName CorporationEmployeeDepartment's table name
func (*CorporationEmployeeDepartment) TableName() string {
	return TableNameCorporationEmployeeDepartment
}
